# Generated by Django 3.2.8 on 2022-05-26 19:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pedagogica', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Docente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.BooleanField(default=True)),
                ('fc', models.DateTimeField(auto_now_add=True)),
                ('fm', models.DateTimeField(auto_now=True)),
                ('um', models.IntegerField(blank=True, null=True)),
                ('nombre', models.CharField(max_length=30)),
                ('apellidoP', models.CharField(max_length=25)),
                ('apellidoM', models.CharField(max_length=25)),
                ('gradoEstudio', models.CharField(max_length=15)),
                ('cedulaP', models.CharField(max_length=18)),
            ],
            options={
                'verbose_name_plural': 'Docentes',
            },
        ),
        migrations.CreateModel(
            name='Grupos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grupo', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Grupo',
            },
        ),
        migrations.CreateModel(
            name='HorarioDocente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.BooleanField(default=True)),
                ('fc', models.DateTimeField(auto_now_add=True)),
                ('fm', models.DateTimeField(auto_now=True)),
                ('um', models.IntegerField(blank=True, null=True)),
                ('horaInicio', models.TimeField()),
                ('horaSalida', models.TimeField()),
                ('fecha', models.CharField(max_length=25)),
                ('uc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'HorarioD',
            },
        ),
        migrations.CreateModel(
            name='UnidadAprendizaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.BooleanField(default=True)),
                ('fc', models.DateTimeField(auto_now_add=True)),
                ('fm', models.DateTimeField(auto_now=True)),
                ('um', models.IntegerField(blank=True, null=True)),
                ('nombre', models.CharField(max_length=50)),
                ('idUaGrupo', models.ManyToManyField(blank=True, related_name='UaGrupo', to='academica.Grupos')),
                ('idUaHorario', models.ManyToManyField(blank=True, related_name='UaHorario', to='academica.HorarioDocente')),
                ('uc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'UnidadesAprendizaje',
            },
        ),
        migrations.CreateModel(
            name='registro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horae', models.DateTimeField(auto_now_add=True)),
                ('horas', models.DateTimeField(null=True)),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academica.unidadaprendizaje')),
                ('nombre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academica.docente')),
            ],
            options={
                'verbose_name_plural': 'registros',
            },
        ),
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.BooleanField(default=True)),
                ('fc', models.DateTimeField(auto_now_add=True)),
                ('fm', models.DateTimeField(auto_now=True)),
                ('um', models.IntegerField(blank=True, null=True)),
                ('horaInicio', models.TimeField()),
                ('horaSalida', models.TimeField()),
                ('fecha', models.CharField(max_length=25)),
                ('dia', models.DateTimeField()),
                ('asignaturas', models.ManyToManyField(blank=True, related_name='HorarioAsg', to='pedagogica.Asignatura')),
                ('docente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academica.docente')),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academica.grupos')),
                ('semestre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pedagogica.semestre')),
                ('uc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Horarios',
            },
        ),
        migrations.AddField(
            model_name='docente',
            name='idDocenteUa',
            field=models.ManyToManyField(blank=True, related_name='docentes', to='academica.UnidadAprendizaje'),
        ),
        migrations.AddField(
            model_name='docente',
            name='uc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
