# Generated by Django 3.2.9 on 2022-05-09 17:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ambitos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcionAmb', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'verbose_name_plural': 'Ambitos',
            },
        ),
        migrations.CreateModel(
            name='Ambitos_Ingreso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcionAmbito', models.CharField(blank=True, max_length=400, null=True)),
            ],
            options={
                'verbose_name_plural': 'Ambitos_Ingreso',
            },
        ),
        migrations.CreateModel(
            name='Ano',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name_plural': 'Anos',
            },
        ),
        migrations.CreateModel(
            name='Asignatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asignatura', models.CharField(blank=True, max_length=100, null=True)),
                ('contenido', models.CharField(blank=True, max_length=100, null=True)),
                ('totalHsTeoricas', models.FloatField(blank=True, null=True)),
                ('totalHsPracticas', models.FloatField(blank=True, null=True)),
                ('total', models.FloatField(blank=True, null=True)),
                ('creditos', models.FloatField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Asignaturas',
            },
        ),
        migrations.CreateModel(
            name='Carrera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carrera', models.CharField(blank=True, max_length=100, null=True)),
                ('nom_corto', models.CharField(blank=True, max_length=100, null=True)),
                ('aano', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pedagogica.ano')),
            ],
            options={
                'verbose_name_plural': 'Carreras',
            },
        ),
        migrations.CreateModel(
            name='Catalogo_Ejes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreejes', models.CharField(blank=True, max_length=400, null=True)),
            ],
            options={
                'verbose_name_plural': 'Nombreejes',
            },
        ),
        migrations.CreateModel(
            name='Certificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion_Cer', models.CharField(blank=True, max_length=400, null=True)),
            ],
            options={
                'verbose_name_plural': 'Certificacion_Cer',
            },
        ),
        migrations.CreateModel(
            name='Certificacion_Est',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificacion_es', models.CharField(blank=True, max_length=400, null=True)),
                ('aCertificacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pedagogica.certificacion')),
            ],
            options={
                'verbose_name_plural': 'Certificacion_Est',
            },
        ),
        migrations.CreateModel(
            name='Competencias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('competencia', models.CharField(blank=True, max_length=200, null=True)),
                ('descripcionCompetencia', models.CharField(blank=True, max_length=400, null=True)),
            ],
            options={
                'verbose_name_plural': 'Competencias',
            },
        ),
        migrations.CreateModel(
            name='Complementarias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complementaria', models.CharField(blank=True, max_length=400, null=True)),
            ],
            options={
                'verbose_name_plural': 'Complementarias',
            },
        ),
        migrations.CreateModel(
            name='Ejes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ejes', models.CharField(blank=True, max_length=100, null=True)),
                ('aasignatura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pedagogica.asignatura')),
                ('acatalogo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pedagogica.catalogo_ejes')),
            ],
            options={
                'verbose_name_plural': 'Ejes',
            },
        ),
        migrations.CreateModel(
            name='Firmas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grado', models.CharField(blank=True, max_length=400, null=True)),
                ('nombre_Completo', models.CharField(blank=True, max_length=400, null=True)),
                ('matricula', models.CharField(blank=True, max_length=400, null=True)),
            ],
            options={
                'verbose_name_plural': 'Firmas',
            },
        ),
        migrations.CreateModel(
            name='Perfil_Egreso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcionPe', models.CharField(blank=True, max_length=400, null=True)),
                ('ambito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pedagogica.ambitos')),
            ],
            options={
                'verbose_name_plural': 'Perfil_Egresos',
            },
        ),
        migrations.CreateModel(
            name='Perfil_Ingreso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ambitos_MCCF', models.CharField(blank=True, max_length=400, null=True)),
                ('aAmbitosIngreso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pedagogica.ambitos_ingreso')),
            ],
            options={
                'verbose_name_plural': 'Perfil_Ingreso',
            },
        ),
        migrations.CreateModel(
            name='Procedimiento_Acre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acreditacion', models.CharField(blank=True, max_length=400, null=True)),
            ],
            options={
                'verbose_name_plural': 'Procedimiento_Acre',
            },
        ),
        migrations.CreateModel(
            name='Procedimientos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('elemento', models.CharField(blank=True, max_length=400, null=True)),
                ('porcentaje', models.CharField(blank=True, max_length=400, null=True)),
            ],
            options={
                'verbose_name_plural': 'Procedimientos',
            },
        ),
        migrations.CreateModel(
            name='Recomendaciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subRecomendaciones', models.CharField(blank=True, max_length=400, null=True)),
            ],
            options={
                'verbose_name_plural': 'Recomendaciones',
            },
        ),
        migrations.CreateModel(
            name='Subrecomendaciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subInciso', models.CharField(blank=True, max_length=400, null=True)),
            ],
            options={
                'verbose_name_plural': 'Subrecomendaciones',
            },
        ),
        migrations.CreateModel(
            name='Semestre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semestre', models.CharField(blank=True, max_length=100, null=True)),
                ('aejes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pedagogica.ejes')),
            ],
            options={
                'verbose_name_plural': 'Semestres',
            },
        ),
        migrations.CreateModel(
            name='Recomendaciones_Met',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recomendaciones', models.CharField(blank=True, max_length=400, null=True)),
                ('aProcedimientos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pedagogica.recomendaciones')),
            ],
            options={
                'verbose_name_plural': 'Recomendaciones_Met',
            },
        ),
        migrations.AddField(
            model_name='recomendaciones',
            name='aSubRecomendaciones',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pedagogica.subrecomendaciones'),
        ),
        migrations.CreateModel(
            name='Procedimiento_Eval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('procedimientos_E', models.CharField(blank=True, max_length=400, null=True)),
                ('aProcedimientos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pedagogica.procedimientos')),
            ],
            options={
                'verbose_name_plural': 'Procedimiento_Eval',
            },
        ),
        migrations.CreateModel(
            name='Plan_Estudio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=400)),
                ('objetivo', models.CharField(max_length=400)),
                ('descripcionPEgre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pedagogica.perfil_egreso')),
                ('pCarrera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pedagogica.carrera')),
                ('pCertificacion_Est', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pedagogica.certificacion_est')),
                ('pComplementarias', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pedagogica.complementarias')),
                ('pFirmas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pedagogica.firmas')),
                ('pPerfil_Ingreso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pedagogica.perfil_ingreso')),
                ('pProcedimiento_Acre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pedagogica.procedimiento_acre')),
                ('pProcedimiento_Eval', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pedagogica.procedimiento_eval')),
                ('pRecomendaciones_Met', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pedagogica.recomendaciones_met')),
            ],
            options={
                'verbose_name_plural': 'Planes_Estudio',
            },
        ),
        migrations.AddField(
            model_name='ano',
            name='asemestre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pedagogica.semestre'),
        ),
        migrations.AddField(
            model_name='ambitos',
            name='aCompetencia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pedagogica.competencias'),
        ),
    ]
